### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by lilacorn** [LazyGon/JailWorker#1]
3:32:38 PM CONSOLE: [INFO] LilAcorn issued server command: /jailworker
3:32:38 PM CONSOLE: thread/ERROR]: null
3:32:38 PM CONSOLE: exception executing command 'jailworker' in plugin JailWorker v3.1.0
3:32:38 PM CONSOLE: Source) [?:1.8.0_211]
3:32:38 PM CONSOLE: java.lang.NoSuchMethodError: java.util.Map.of()Ljava/util/Map;

let me know if you need any more info, this is all i could see in the console.

**Comment by LazyGon** [comment]
Your java version is 8.
And JailWorker you are using requires java9. (Method Map.of() is since java9)
Now new version of JailWorker is supported java8.
Please update it!
