### ISSUE TITLE
Not enough arguments

### ISSUE THREAD

**Issue by lilacorn** [LazyGon/JailWorker#2]
java updated to 9

but when i go to type /jw create jailname
it tosses up not enough arguments 
i already have pos 1 and pos 2 with WE selecting the places.

i do not see any errors on the log to paste any errors.

**Comment by LazyGon** [comment]
Sry for late reply because my real life is a little busy...

OK, I added feature that prints usage of command when jailworker got command syntax error.
And changed /jw create ~ command syntax.
From new version, you can use /jw create jailname

Thanks for reporting!
