### ISSUE TITLE
Creative

### ISSUE THREAD

**Issue by lilacorn** [LazyGon/JailWorker#3]
are you able to set it to where if someone is in creative to be knocked out of creative when jailed? when you jail someone who is in creative they are in creative and can break the blocks way to easy.

**Comment by LazyGon** [comment]
On next update (3.3.10), when creative player is jailed, their gamemode is set to survival.
If this way is not suitable for your server, plz recreate issue.

**Comment by lilacorn** [comment]
thanks! i willle you know if this up coming update resolves this.

**Comment by LazyGon** [comment]
Updated JailWorker, and close issue...
